name: Build and Deploy to Azure

on:
  push:
    branches:
      - master  # Използваш master клона

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    # Setup .NET Core SDK
    - name: 'Setup .NET Core SDK'
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    # Restore dependencies
    - name: 'Restore dependencies'
      run: dotnet restore './MovieStoreMvc.csproj'  # Коригираният път

    # Build the project
    - name: 'Build the project'
      run: dotnet build './MovieStoreMvc.csproj' --configuration Release --no-restore  # Коригираният път

    # Publish the project
    - name: 'Publish the project'
      run: dotnet publish './MovieStoreMvc.csproj' --configuration Release --output ./output  # Коригираният път

    # Use Azure login action with the credentials from secrets
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Deploy to Azure Web App
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'MovieStoreApp'
        slot-name: 'production'
        package: './output'
